### ISSUE TITLE
ERROR: opening elevation database

### ISSUE THREAD

**Issue by moorsey** [usedbytes/osgrid#2]
Not sure if the way OS provides this data has changed since this project was created.  But just attempting on Windows using:

`D:\osgrid-master\cmd\osmodel>osmodel.exe mesh --elevation D:\osgrid-master\terr50_gagg_gb -w 5000 -o test.stl ST 46697 53996`

and I am seeing

`ERROR: opening elevation database: CreateFile ~\terr50_gagg_gb\data: The system cannot find the path specified.`

Thanks for the project, seems chronically under used, as it seems to be the only tool for the job!  Thanks for sharing this work!

**Comment by usedbytes** [comment]
Hi, thanks for the report. I’ve never tried this on Windows.

It looks like `os.Stat` calls `CreateFile` on Windows, so it’s possibly failing in there for some reason. It’s very curious that the failing path starts with `~`, perhaps I’ve got a bug with handling Windows paths.

Can you please confirm that `D:\osgrid-master\terr50_gagg_gb\data` exists?

I’ll have a go at setting this up on a Windows machine in the next couple of days

**Comment by moorsey** [comment]
Many thanks for the reply

Yes, can confirm the directory does exist

Wouldn't want to waste your time on a Windows spesific issue, will have a go on Linux over the weekend also anyway

**Comment by usedbytes** [comment]
Hi, is the error message above definitely what you see? I've identified another bug where it unconditionally attempts to open the "raster" database, even if you don't ask for texture - I've pushed a fix for that, but the error that causes is: `ERROR: opening raster database`, not `ERROR: opening elevation database` 

I've been trying on Windows, and it seems to work OK (with the above fix):

```
osmodel.exe mesh --elevation G:\terr50_gagg_gb -w 5000 -o test.stl ST 46697 53996
```

**Comment by moorsey** [comment]
Just tried with latest code and seems to be working fine now, much appreciated
